version: 2

sources: 
  - name: raw_data   # some name it according to WH it's from e.g. bigquery_sources/raw_data
    description: raw data from bigquery
    database: terraform-demo-485118
    schema: zoomcamp

    tables:
    - name: green_tripdata
    - name: yellow_tripdata
